apiVersion: apps/v1
kind: Deployment
metadata:
  name: microone-deployment 
  labels:
    app: microservice-two   
    env: production
    project: user-management 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-two 
  template:
    metadata:
      labels:
        app: microservice-two  
    spec:
      containers:
        - name: microservice-two 
          image: shahabaz4573/microservice_two:2.0
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-two  
  labels:
    app: microservice-two  
    env: production
    project: user-management  
spec:
  type: NodePort
  selector:
    app: microservice-two  
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: 30003
