apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtwo-deployment
  labels:
    app: microservice-one
    env: production
    project: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-one
  template:
    metadata:
      labels:
        app: microservice-one
    spec:
      containers:
        - name: microservice-one
          image: shahabaz4573/microservice_one:1.0
          ports:
            - containerPort: 50001

---

apiVersion: v1
kind: Service
metadata:
  name: microservice-one
  labels:
    app: microservice-one
    env: production
    project: user-management
spec:
  type: ClusterIP
  selector:
    app: microservice-one
  ports:
    - port: 50001
      targetPort: 50001
